### PR TITLE
Minor lighting Fixes

### PR DESCRIPTION
**Pull request by MehranAkbarii**
1.remove dark filter from GTA IV and yellow filter from TLAD (just use original timecyc.dat file from TBOGT) 
2.fix interior colors for example some of Niko home items that appears black by default

Grand Theft Auto 4 Screenshot 2023 06 25 - 02 47 38 40

Grand Theft Auto 4 Screenshot 2023 06 25 - 02 47 18 73

Grand Theft Auto 4 Screenshot 2023 06 25 - 02 47 25 84

### CODE REVIEW

**Comment by MehranAkbarii** [comment]
seems like these changes did not interest you to merge them to your project , anyway I just tried to help and I shared my workaround to get rid of game's messy lighting (annoying filters)

**Comment by MagicAl6244225** [comment]
@MehranAkbarii They probably didn't accept your suggestions because you're suggesting a design change to the game but this mod is mainly to fix bugs and broken features.

Your screenshots got my attention because the dark objects in the Algonquin safehouse have no ambient light on them but there's light on the floor and on Niko's feet when he stands there. It looks wrong but I checked on Xbox and it's the same, and the headlight shows they render correctly, they just have no light. A "fix" might change the ambient light on the objects to be the same as on the floor and player, but there's no version of the game that shows us Rockstar intended differently than how it is.

Xbox screenshots:
6-25-2023_2-58-20_PM-atijyzmg
6-25-2023_2-58-16_PM-ktsqb3hi
6-25-2023_3-09-37_PM-jewql0wz
6-25-2023_3-09-42_PM-jrxvh0nc

**Comment by ThirteenAG** [comment]
We need 3 separate timecyc files for screen filter option.
Screen Filter: IV, TLAD, TBOGT
IV: default timecyc, timecyc TLAD filter, timecyc TBOGT filter
TLAD: default timecyc, timecyc IV filter, timecyc TBOGT filter
TBOGT: default timecyc, timecyc TLAD filter, timecyc IV filter
If you're up for the task, let us know.

**Comment by MehranAkbarii** [comment]
Ok thanks , about timecyc I actually copied TBOGT to IV and TLAD becuase only TBOGT one has no dark and yellow filters.

**Comment by ThirteenAG** [comment]
We need them edited accordingly.

**Comment by MehranAkbarii** [comment]
I can not see any issues when I used TBOGT one , but I can rewrite IV and TLAD values based on that TBOGT one.

**Comment by MehranAkbarii** [comment]
I understood

**Comment by MagicAl6244225** [comment]
> We need 3 separate timecyc files for screen filter option. Screen Filter: IV, TLAD, TBOGT IV: default timecyc, timecyc TLAD filter, timecyc TBOGT filter TLAD: default timecyc, timecyc IV filter, timecyc TBOGT filter TBOGT: default timecyc, timecyc TLAD filter, timecyc IV filter If you're up for the task, let us know.

In theory this could be done in real time but I lack the coding knowledge. Here's the color theory: you want timecyc 1 to be tinted like timecyc 2 without changing brightness or saturation unintentionally. A real-time conversion would read the current ColourCorrectRGB values simultaneously from the corresponding weather/time of timecyc 1 and timecyc 2. Call these two values R1G1B1 and R2G2B2. Convert both RGB values to HSL, call the results H1S1L1 and H2S2L2, and from those create a new HSL value that is H2S1L1 (swapping the hue only), and convert that H2S1L1 to RGB and that result would be the desired, re-tinted ColourCorrectRGB, having the same saturation and luminance of the original timecyc value with the hue of the other one.

This method could be used for a fourth no-tint option which would be done by converting R1G1B1 to H1S1L1, changing the S value to a 0 to get H1S0L1, and converting that to RGB to get your new ColourCorrectRGB with tint removed but original luminance preserved, preserving how the original luminance might interact with the weather effect.

In the absence of a real-time solution, I could generate the 6 to 9 alternate timecyc files based on this method.

**Comment by ThirteenAG** [comment]
> In the absence of a real-time solution, I could generate the 6 to 9 alternate timecyc files based on this method.

I don't wanna bother with this much, but I think the option to have different screen filters with original timecyc otherwise would be nice, even if made via multiple timecyc files.

**Comment by MagicAl6244225** [comment]
[Timecyc HSL project.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/11863970/Timecyc.HSL.project.zip)
Here are the combinations of three timecycs and three colors plus no-tint options. During some cloudy, rainy or night weathers there may be no difference in filter so the user may not see immediate feedback if a filter-changing feature is used at those times.

**Comment by ThirteenAG** [comment]
> [Timecyc HSL project.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/11863970/Timecyc.HSL.project.zip) Here are the combinations of three timecycs and three colors plus no-tint options. During some cloudy, rainy or night weathers there may be no difference in filter so the user may not see immediate feedback if a filter-changing feature is used at those times.

Thanks, should be included in the next release.

https://imgur.com/lMXCfJr

**Comment by MagicAl6244225** [comment]
Nice! If you can switch .dat like that can you do Dirt Level 0,1,2 alternating vehicle.ide

**Pull request closed without merging**
