### PR TITLE
Backport the new changes

### PR DESCRIPTION
**Pull request by Zolika1351**
Backported the 360FPS cap, loadscreen check and DoF toggle
also ported the proper timecycle refreshing code since my old hack for it was unstable

### CODE REVIEW

**Comment by Tomasak** [comment]
Menu bug in main menu and recordings menu bug was checked and fixed?

**Comment by longaru** [comment]
> Backported the 360FPS cap, loadscreen check and DoF toggle also ported the proper timecycle refreshing code since my old hack for it was unstable

Ps : GTA IV needs timecycle speed refresh like in real life , not freeze .. GTA V Enhanced Native Trainer - time speed 1\1 sec .. &  3-5 sec in game etc . ( NOT freeze , because enb have adaptation bug if timecycle speed freezed ) .

Very needed :(

Thx for Your work )

**Comment by Zolika1351** [comment]
> Menu bug in main menu and recordings menu bug was checked and fixed?

No idea what causes the video editor bug, and I don't know what the "menu bug in main menu" is

**Comment by Zolika1351** [comment]
> #112 is the main menu bug

Doesn't happen here, tried with both 1070 and 1080 using the latest ZPatch with FF in both the root and update folders, with/without OverloadFromFolderDLL, sounds more like user error than a mod bug

**Comment by Tomasak** [comment]
Idk then
Also when will you add some of those fixes from zpatch in ff as you talked about it with Ash? :)

**Comment by Zolika1351** [comment]
> Idk then Also when will you add some of those fixes from zpatch in ff as you talked about it with Ash? :)
Not in this PR as this is just for backporting existing stuff
Though I thought the code snippets I sent made it over? Could've added those already on you guys' end, otherwise I'll implement them when I wanna focus on IV again

**Comment by Tomasak** [comment]
only one, and tbh i expected more fixes than just sleep patch

**Comment by SpiffyJUNIOR** [comment]
bump, but are there any plans to provide builds for this or is this branch still too preliminary?

**Comment by Tomasak** [comment]
Link for latest download for nonCE version is on pre-CE branch in installation section
image
it includes latest changes from this pull

**Pull request merged**
