### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by Patrxgt**
If needed, here's properly mapped character set for Polish font file for X GXT Editor: [link](https://mega.nz/file/Wo9xgITZ#QaD2NPtpVUcuCgSG-TbN4si-xi8qXdgNYDw6xdtAcl4)

### CODE REVIEW

**Comment by ThirteenAG** [comment]
There's no polish in the game code.

**Comment by Patrxgt** [comment]
There's a fan polish translation, that usually replaces american.gxt, but I'm making an update to it for proper Fusion Fix support.

BTW. Should I rename the .gxt file to polish.gxt or languagepl.gxt? Description in the release section of this feature is quite unclear.

**Comment by ThirteenAG** [comment]
> There's a fan polish translation, that usually replaces american.gxt, but I'm making an update to it for proper Fusion Fix support.

Then include it in that update, and you'd have to replace americanFF, of course.

> BTW. Should I rename the .gxt file to polish.gxt or languagepl.gxt? Description in the release section of this feature is quite unclear.

It won't be loaded with any name, I don't know why you thought just putting that file there will do anything. GXT compiler doesn't even have support for polish. The feature only works with what officially supported in exe.

**Comment by Patrxgt** [comment]
> I don't know why you thought just putting that file there will do anything.

Because it's a feature advertised on the release page of 3.0 update?

**Comment by ThirteenAG** [comment]
It's not... advertised? We just stated that we translated some stuff and that's all.

For unofficial translations there's no need to put anything into fusion fix, just distribute them or a fix for them separately. There's no code to load polishFF or anything of the sort.

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/blob/master/source/comvars.ixx#L12-L21

**Pull request closed without merging**
