### PR TITLE
Add issue forms for bug reports and feature requests

### PR DESCRIPTION
**Pull request by SandeMC**
Because I think there's too many junk issues. Suggest any changes if this doesn't fit your idea.

### CODE REVIEW

**Comment by SandeMC** [comment]
Sure, ignore it.

**Comment by Meriato** [comment]
Don't know why this wasn't merged already, it is certainly very helpful.

**Comment by RecklessGlue540** [comment]
@ThirteenAG said it's in the works....
Before this, @Tomasak made a pull request with something similar. In the end, he took it back...

**Comment by SandeMC** [comment]
The fact it's in the works doesn't deny that there's an existing pull request that already does it. If he's not happy with some parts of it, there's this thing called comments and reviews which he can submit for any changes to be done. That is, no ego is involved.

**Comment by SandeMC** [comment]
Very professional github usage.

**Comment by Tomasak** [comment]
Idk what makes you feel so entitled for anything on free of charge product. This mod is aimed at CE, with nonCE support not being promised at all. So if I see one more complaint against FusionTeam from you every again public or private, you get permabanned from here no refunds, you protagonist syndrome having annoyance.

**Comment by SandeMC** [comment]
Whatever suits you.

**Comment by ThirteenAG** [comment]
For the record, I have no idea who this person above is and what he imagines happening here. I have better things to do than deal with this.

**Pull request closed without merging**
